### ISSUE TITLE
motif.hg19.CTCF.chr22

### ISSUE THREAD

**Issue by tamerawwad** [ibn-salem/chromloop#2]
Hi,
Thank you so much for developing such interesting package. I am r beginner and of course I have some questions ... 
I would like to use this package for mouse CTCF motif orientation .. how to get the mouse ctcf.motif.ch18  file??
thanks much

**Comment by ibn-salem** [comment]
Hi @tamerawwad 
thanks for your interest in the seven7 package!
The CTCF motif sites are input data required from the user. Only an example dataset for the human genome is provided with the seven7 package. We obtained these motifs locations from the JASPAR genome browser tracks: 
https://github.com/wassermanlab/JASPAR-UCSC-tracks
From the readme, it seems that they are also preparing motif tracks for the mouse genome assembly mm10. You might kindly ask there when they plan to release this data.

**Comment by istudysheep** [comment]
Hi, really cool package.  Any ideas on how to get started on a custom motif location file.  I study a completely different species (sheep) and was hoping I could get your package working one way or another. I have ChIP-seq data on two replicates for CTCF.  Can I use HOMER to generate the motifs and get a motif location bed file.  Or will that not work as I am using the same data to generate the motifs as I am loading into sevenC???

**Comment by ibn-salem** [comment]
Hi, 
thanks for the interest in 7C and thanks for your question.
Yes, sure if you have CTCF motif locations as BED file you can load them into R by

```
motifs <- rtracklayer::import.bed("path/to/motif_locations.bed")
```

In general, I would recommend to not only use the motif locations within the ChIP-seq peaks. If you identified the CTCF motif for your species, you can use the motif model to scan the genome for all significant motif hits and use these locations as input to 7C. This might allow 7C to also predict loops for regions with minor background ChIP-seq signals.
